(function($){$.fn.j360=function(options){var defaults={clicked:false,currImg:1}
var options=jQuery.extend(defaults,options);return this.each(function(){var $obj=jQuery(this);var aImages={};var bImages={};$obj.css({'overflow':'hidden','cursor':'e-resize'});$overlay=$obj.clone(true);$overlay.html('').attr('id','').attr('class','view_overlay');$overlay.css({'position':'absolute','top':0,'left':0,'width':'100%','height':'100%','background':'url('+root+'static/images/loader.gif) center center no-repeat'});$obj.after($overlay);var imageTotal=0,bimageTotal=0;jQuery('img',$obj).each(function(){aImages[++imageTotal]=jQuery(this).attr('src');preload(jQuery(this).attr('src'));});jQuery('#intro-page .img-mirror .img_mr img').each(function(){bImages[++bimageTotal]=jQuery(this).attr('src');preload(jQuery(this).attr('src'));})
var imageCount=0;jQuery('.preload_img').load(function(){if(++imageCount==imageTotal){$('.view_overlay').animate({'opacity':0},500);$obj.find($('img[src="'+aImages[1]+'"]')).show().siblings().hide();$overlay.bind('mousedown touchstart',function(e){if(e.type=="touchstart"){options.currPos=window.event.touches[0].pageX;}else{options.currPos=e.pageX;}
options.clicked=true;return false;});jQuery(document).bind('mouseup touchend',function(){options.clicked=false;});jQuery('.next-360, .prev-360').bind('mousedown',function(){options.clicked=true;});jQuery('.next-360, .prev-360').bind('mouseup',function(){options.clicked=false;});jQuery('.next-360').bind('mousedown',function(e){e.stopPropagation();if(options.clicked){options.currImg--;if(options.currImg<1){options.currImg=imageTotal;}
$obj.find($('img[src="'+aImages[options.currImg]+'"]')).show().siblings().hide();$('#intro-page .img-mirror .img_mr').find($('img.img_'+options.currImg)).show().siblings().hide();};});jQuery('.prev-360').bind('mousedown',function(e){e.stopPropagation();if(options.clicked){options.currImg++;if(options.currImg>imageTotal){options.currImg=1;}
$obj.find($('img[src="'+aImages[options.currImg]+'"]')).show().siblings().hide();$('#intro-page .img-mirror .img_mr').find($('img.img_'+options.currImg)).show().siblings().hide();};});jQuery(document).bind('mousemove touchmove',function(e){if(options.clicked){var pageX;if(e.type=="touchmove"){pageX=window.event.targetTouches[0].pageX;}else{pageX=e.pageX;}
var width_step=2;if(Math.abs(options.currPos-pageX)>=width_step){if(options.currPos-pageX>=width_step){options.currImg++;if(options.currImg>imageTotal){options.currImg=1;}}else{options.currImg--;if(options.currImg<1){options.currImg=imageTotal;}}
options.currPos=pageX;$obj.find($('img[src="'+aImages[options.currImg]+'"]')).show().siblings().hide();$('#intro-page .img-mirror .img_mr').find($('img.img_'+options.currImg)).show().siblings().hide();}}});}});if(jQuery.browser.msie||jQuery.browser.mozilla||jQuery.browser.opera||jQuery.browser.safari){jQuery(window).resize(function(){onresizeFunc($obj,$overlay);});}else{var supportsOrientationChange="onorientationchange"in window,orientationEvent=supportsOrientationChange?"orientationchange":"resize";window.addEventListener(orientationEvent,function(){onresizeFunc($obj,$overlay);},false);}
onresizeFunc($obj,$overlay)});};})(jQuery)
function active_360(index,call){var current=$('#intro-page .car .js_car img').not(':hidden').index();if(current==index){if(typeof(call)=="function"){call();}
return false;}
var time=setInterval(function(){current++;if(current>8){current=0;}
if(current!=index){$('#intro-page .car .js_car img').eq(current).show().siblings().hide();$('#intro-page .img-mirror .img_mr').each(function(){$('img',this).eq(current).show().siblings().hide();});}else{clearInterval(time);if(typeof(call)=="function"){call();}}},200);}
function onresizeFunc($obj,$overlay){$overlay.css({'margin-top':0,'top':0,'left':0});jQuery('#colors_ctrls').css({'top':0,'left':0});}
function preload(image){if(typeof document.body=="undefined")return;try{var div=document.createElement("div");var s=div.style;s.position="absolute";s.top=s.left=0;s.visibility="hidden";document.body.appendChild(div);div.innerHTML="<img class=\"preload_img\" src=\""+image+"\" />";}catch(e){}}